---
title: TI10KO
timezone: UTC
collections:
  news:
    title: News
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Maksym Titenko
description: Web Developer from Somewhere
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: barryclark/jekyll-now
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: jekyllrb
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: https-titenko-github-io
google_analytics: 
url: https://titenko.github.io
baseurl: 
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
