<<<<<<< HEAD
#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: GeekHub

# Short bio or description (displayed in the header)
description: Web Developer from Somewhere

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: titenko
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: jekyllrb
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://titenko.github.io/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
=======
---
title: GeekHub
timezone: Europe/Warsaw
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: barryclark/jekyll-now
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: jekyllrb
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
email: titenko.m@gmail.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: https://titenko.github.io/
twitter_username: jekyllrb
github_username: titenko
theme: minima
plugins:
- jekyll-feed
permalink: "/:title/"
>>>>>>> 0f7169755bb89ec2954d2f4bd74632653dee559b
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
