---
title: GeekHub
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
header_title: GeekHub
author: Maksym Titenko
email: titenko.m@gmail.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: https://github.com/titenko/titenko.github.io
<<<<<<< HEAD
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: barryclark/jekyll-now
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: jekyllrb
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
=======
twitter_username: 
github_username: 
>>>>>>> 2b0e9f3c08f9e698e0abb0ef50b5057f33e2ccfd
theme: minima
plugins:
- jekyll-feed
